### ISSUE TITLE
Game that wont install to my hard drive

### ISSUE THREAD

**Issue by l-guille** [GDX-X/PFS-BatchKit-Manager#10]
First of all, i want to thanks the creater of this project, i realy liked the program and now, its my prefered one.

I dont have actualy a complaint, i have a question, i tried this ps2 iso and it gave this mensage, and im not really sure how to do what the program is asking me. I tried another iso and it worked, but i alredy tried 4 differrent isos from "metal gear solid 2: sons of liberty" and none worked, the all gaved me this mensage.

So im just asking what i need to do or what this mensage means.

![unknown](https://user-images.githubusercontent.com/101019217/156898076-cb973a95-8389-4c17-9f7a-7d60f8257079.png)

**Comment by GDX-X** [comment]
Hey thank you for your feedback!

yes it's a bug that has been fixed in a new version that will be released soon. while waiting for me to publish it https://raw.githubusercontent.com/GDX-X/PFS-BatchKit-Manager/main/PFS-BatchKit-Manager/BAT/hdl_dump.exe 

copy this file in the BAT folder if you do not see it you must activate the hidden folder

this should fix the problem

**Comment by l-guille** [comment]
Thanks, Keep up with good work, i apreciate your job!!! 
Congratulations from Brazil!!

**Comment by GDX-X** [comment]
Thanks you! glad you like it!
