### ISSUE TITLE
CHT files import bug

### ISSUE THREAD

**Issue by T3ll3S-05** [GDX-X/PFS-BatchKit-Manager#35]
Hello, when I imported all of my .CHT files to the internal HD, some games would not launch at all on OPL. When I checked some of the .CHT files I noticed some (or all, need to check) were corrupted. As an example, one file added a new line with a half the value from the previous line + random characters, the patch was 2 lines but somehow it had 3 lines (last line wasn't neither completed nor correct). So far I fixed one file and the game booted again, the game was Shrek 2. This also happened with Tekken 5 but I already fixed the codes for that game. Thanks in advance.

**Comment by GDX-X** [comment]
Hello ,

There are two possibilities

1) Your partition is corrupted is corrupted all copied files

2) The CHT file was already like this (if you are using widescreen cheats, the problem may be that some games have revisions and so if you use a cheat from a different revision, the game may crash due to different address memory)

Personally I have not used it I find it useless in addition to bringing compatibility problems

**Comment by T3ll3S-05** [comment]
Well, they weren't messed up, what I did to end up here was copying the folders and games from the external hd to laptop (I don't have 2 HDD cases), format it, install fhdb + OPL and import everything back to the internal hdd, maybe it corrupted? Im going to see and fix how many got affected
